name: .NET Test Automation CI

on:
  workflow_dispatch: # Allows manual trigger
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests and generate TRX report
        run: |
          mkdir -p TestResults
          dotnet test --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults
        continue-on-error: true  # <-- IMPORTANT: don't stop workflow if tests fail

      - name: Publish TRX Test Results
        uses: actions/upload-artifact@v4
        with:
          name: trx-test-results
          path: ./TestResults/test_results.trx

      - name: Install ReportGenerator and Generate HTML Report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator \
            "-reports:./TestResults/test_results.trx" \
            "-targetdir:./TestResults/Report" \
            "-reporttypes:HtmlInline_AzurePipelines"

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: ./TestResults/Report
